/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2df4bb58318df445a99f385f92378e3c)
interface __BaseEnv_Env {
	METRICS: AnalyticsEngineDataset;
	AFT_API_BASE: "https://api.aft.page";
	API: Fetcher /* aft-page-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AFT_API_BASE">> {}
}
