#!/usr/bin/env bash
#
# Destroy test/smoke/debug sites via the aft.page DELETE endpoint.
# This performs a full cleanup (D1 rows + R2 objects + KV blobs), unlike a raw
# D1 delete which would leave orphaned storage behind.
#
# Auth: the endpoint is owner-only and reads your `aft_session` cookie.
#   1. Log in at https://aft.page in your browser.
#   2. DevTools -> Application -> Cookies -> https://api.aft.page
#   3. Copy the value of the `aft_session` cookie.
#
# Usage:
#   AFT_SESSION="<cookie-value>" ./scripts/destroy-test-sites.sh
#   AFT_SESSION="<cookie-value>" ./scripts/destroy-test-sites.sh --dry-run
#
set -euo pipefail

API="${AFT_API:-https://api.aft.page}"
DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

if [[ "$DRY_RUN" == "0" && -z "${AFT_SESSION:-}" ]]; then
  echo "error: set AFT_SESSION to your aft_session cookie value." >&2
  exit 1
fi

# Bucket A — test / smoke / debug artifacts (autogenerated slugs, 0-1 deploys).
SLUGS=(
  auth-smoke-1785160943
  e2e-1785161394
  claim-debug-tmp
  _login
  8urp7wjv
  bi1u9g6r
  movbu0k6
  qhvthavv
  f1gdz3b3
  rz91f43z
  aft-api-bundle
  aft-api-bundle2
  svg-quality
  svg-preview
  expense-w3-98977
)

ok=0
fail=0
for slug in "${SLUGS[@]}"; do
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "[dry-run] would destroy: $slug"
    continue
  fi
  code=$(curl -sS -o /tmp/aft_destroy_body -w "%{http_code}" \
    -X DELETE "$API/v1/sites/$slug" \
    -H "Cookie: aft_session=$AFT_SESSION")
  body=$(cat /tmp/aft_destroy_body)
  if [[ "$code" == "200" ]]; then
    echo "destroyed  $slug"
    ok=$((ok + 1))
  elif [[ "$code" == "404" ]]; then
    echo "gone/404   $slug (already deleted)"
    ok=$((ok + 1))
  else
    echo "FAILED     $slug -> HTTP $code $body" >&2
    fail=$((fail + 1))
  fi
done

rm -f /tmp/aft_destroy_body
echo "---"
echo "done: $ok ok, $fail failed"
[[ "$fail" == "0" ]]
